CREATE TABLE IF NOT EXISTS users (
  id                   INT AUTO_INCREMENT PRIMARY KEY,
  email                VARCHAR(255) UNIQUE NOT NULL,
  password_hash        TEXT,
  name                 TEXT,
  photo_url            TEXT,
  role                 VARCHAR(50) CHECK(role IN ('entrepreneur', 'investor')),
  is_verified          TINYINT(1) DEFAULT 0,
  otp_code             TEXT,
  otp_expires_at       DATETIME NULL,
  reset_token          TEXT,
  reset_token_expires  DATETIME NULL,
  oauth_provider       VARCHAR(50) CHECK(oauth_provider IN ('google', 'linkedin')),
  oauth_provider_id    TEXT,
  two_factor_secret    TEXT,
  two_factor_enabled   TINYINT(1) DEFAULT 0,
  verification_status  VARCHAR(20) DEFAULT 'none' CHECK(verification_status IN ('none','pending','verified','rejected')),
  deleted_at           DATETIME NULL,
  push_token           VARCHAR(500),
  is_premium           BOOLEAN DEFAULT 0,
  premium_expires_at   DATETIME,
  login_attempts       INT DEFAULT 0,
  locked_until         DATETIME NULL,
  last_active_at       DATETIME NULL DEFAULT NULL,
  swipe_count          INT DEFAULT 0,
  swipe_count_date     DATE NULL,
  has_seen_onboarding  TINYINT(1) NOT NULL DEFAULT 0,
  bio                  TEXT,
  skills               TEXT,
  hobbies              TEXT,
  role_type            VARCHAR(50),
  investment_domain    TEXT,
  preferred_stage      VARCHAR(20) CHECK(preferred_stage IN ('idea','mvp','growth','scale')),
  max_investment       DECIMAL(15,2),
  portfolio_url        VARCHAR(500),
  linkedin_url         VARCHAR(500),
  experience           TEXT,
  cv_url               VARCHAR(500),
  created_at           DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
