ALTER TABLE users ADD COLUMN IF NOT EXISTS is_premium BOOLEAN DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS premium_expires_at DATETIME;
ALTER TABLE swipes ADD COLUMN IF NOT EXISTS is_super_like BOOLEAN DEFAULT 0;
